name: Hide Sensitive Information
on: push
jobs:
  print-secret-apikey:
    runs-on: ubuntu-latest
    steps:
      - name: Add key
        run: node -e "console.log('ok')"
        env:
         _OMBD_APIKEY: ${{ secrets._OMBD_APIKEY }}
