name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    name: apikey
    env: # Or as an environment variable
      _OMBD_APIKEY: ${{ secrets._OMBD_APIKEY }}