name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Add Mask
        run: node -e "console.log(process.env._OMBD_APIKEY)"
        env:
         _OMBD_APIKEY: ${{ secrets._OMBD_APIKEY }}
