name: Sensitive Information
on: push
jobs:
  print-secret-apikey:
    runs-on: ubuntu-latest
    steps:
      - name: apikey
        run: node -e "console.log(process.env._APIKEY)"
        env:
         _APIKEY: ${{ secrets._APIKEY }}